//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotosItalika
    {
        public int idMotos { get; set; }
        public string SKU { get; set; }
        public string Fert { get; set; }
        public string Modelo { get; set; }
        public int IdTipo { get; set; }
        public string NumSerie { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Tipo Tipo { get; set; }
    }
}
